# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CLEAUT.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labela = QtWidgets.QLabel(self.centralwidget)
        self.labela.setGeometry(QtCore.QRect(70, 80, 67, 17))
        self.labela.setObjectName("labela")
        self.labelb = QtWidgets.QLabel(self.centralwidget)
        self.labelb.setGeometry(QtCore.QRect(320, 80, 67, 17))
        self.labelb.setObjectName("labelb")
        self.valuea = QtWidgets.QLabel(self.centralwidget)
        self.valuea.setGeometry(QtCore.QRect(70, 120, 181, 17))
        self.valuea.setObjectName("valuea")
        self.valueb = QtWidgets.QLabel(self.centralwidget)
        self.valueb.setGeometry(QtCore.QRect(320, 120, 191, 17))
        self.valueb.setObjectName("valueb")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(60, 190, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labela.setText(_translate("MainWindow", "Symbol A"))
        self.labelb.setText(_translate("MainWindow", "Symbol B"))
        self.valuea.setText(_translate("MainWindow", "TextLabel"))
        self.valueb.setText(_translate("MainWindow", "TextLabel"))
